In [50]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [51]:
df=pd.read_csv('sonar_dataset.csv',header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [52]:
df.shape

(208, 61)

In [53]:
import warnings
warnings.filterwarnings('ignore')

In [54]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [55]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [57]:
x=df.drop([60],axis='columns')
x.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
20    float64
21    float64
22    float64
23    float64
24    float64
25    float64
26    float64
27    float64
28    float64
29    float64
30    float64
31    float64
32    float64
33    float64
34    float64
35    float64
36    float64
37    float64
38    float64
39    float64
40    float64
41    float64
42    float64
43    float64
44    float64
45    float64
46    float64
47    float64
48    float64
49    float64
50    float64
51    float64
52    float64
53    float64
54    float64
55    float64
56    float64
57    float64
58    float64
59    float64
dtype: object

In [59]:
y=df[[60]]
y.dtypes

60    object
dtype: object

In [60]:
y=pd.get_dummies(y,drop_first=True)
y

     60_R
0       1
1       1
2       1
3       1
4       1
..    ...
203     0
204     0
205     0
206     0
207     0

[208 rows x 1 columns]

In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)
len(x_train)

166

In [62]:
len(y_train)

166

In [84]:
model=keras.Sequential([
     keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dropout(0.5),
     keras.layers.Dense(30,activation='relu'),
    keras.layers.Dropout(0.5),
     keras.layers.Dense(15,activation='relu'),
    keras.layers.Dropout(0.5),
     keras.layers.Dense(1,activation='sigmoid')
    
])
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])
model.fit(x_train,y_train,epochs=70,batch_size=8)

Epoch 1/70
21/21 [==============================] - 2s 3ms/step - loss: 0.7113 - accuracy: 0.5301
Epoch 2/70
21/21 [==============================] - 0s 3ms/step - loss: 0.7138 - accuracy: 0.5120
Epoch 3/70
21/21 [==============================] - 0s 3ms/step - loss: 0.7041 - accuracy: 0.4940
Epoch 4/70
21/21 [==============================] - 0s 3ms/step - loss: 0.7001 - accuracy: 0.4940
Epoch 5/70
21/21 [==============================] - 0s 3ms/step - loss: 0.7015 - accuracy: 0.5422
Epoch 6/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.5542
Epoch 7/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6789 - accuracy: 0.5301
Epoch 8/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6885 - accuracy: 0.5482
Epoch 9/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6969 - accuracy: 0.5422
Epoch 10/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6771 - accuracy: 0.5723
Epoch 11/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6659 - accuracy: 0.5723
Epoch 12/70
21/21 [==============================] - 0s 4ms/step - loss: 0.6845 - accuracy: 0.5723
Epoch 13/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6635 - accuracy: 0.6024
Epoch 14/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6581 - accuracy: 0.5904
Epoch 15/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6492 - accuracy: 0.6084
Epoch 16/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6824 - accuracy: 0.6205
Epoch 17/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6599 - accuracy: 0.5723
Epoch 18/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6463 - accuracy: 0.6084
Epoch 19/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6456 - accuracy: 0.6325
Epoch 20/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6487 - accuracy: 0.5904
Epoch 21/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6317 - accuracy: 0.6325
Epoch 22/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6315 - accuracy: 0.6325
Epoch 23/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6407 - accuracy: 0.6566
Epoch 24/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6081 - accuracy: 0.6747
Epoch 25/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6155 - accuracy: 0.6265
Epoch 26/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6127 - accuracy: 0.6687
Epoch 27/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6409 - accuracy: 0.6867
Epoch 28/70
21/21 [==============================] - 0s 4ms/step - loss: 0.5989 - accuracy: 0.6867
Epoch 29/70
21/21 [==============================] - 0s 3ms/step - loss: 0.6092 - accuracy: 0.6446
Epoch 30/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5750 - accuracy: 0.7169
Epoch 31/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5913 - accuracy: 0.7048
Epoch 32/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5525 - accuracy: 0.7349
Epoch 33/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5651 - accuracy: 0.6747
Epoch 34/70
21/21 [==============================] - 0s 4ms/step - loss: 0.5609 - accuracy: 0.7410
Epoch 35/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5425 - accuracy: 0.6928
Epoch 36/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5443 - accuracy: 0.7048
Epoch 37/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5115 - accuracy: 0.7590
Epoch 38/70
21/21 [==============================] - 0s 4ms/step - loss: 0.5640 - accuracy: 0.7289
Epoch 39/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5807 - accuracy: 0.7470
Epoch 40/70
21/21 [==============================] - 0s 4ms/step - loss: 0.5380 - accuracy: 0.7590
Epoch 41/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4730 - accuracy: 0.7831
Epoch 42/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5273 - accuracy: 0.7530
Epoch 43/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4674 - accuracy: 0.7530
Epoch 44/70
21/21 [==============================] - 0s 3ms/step - loss: 0.5321 - accuracy: 0.7229
Epoch 45/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4820 - accuracy: 0.7711
Epoch 46/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4807 - accuracy: 0.8434
Epoch 47/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4817 - accuracy: 0.7530
Epoch 48/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4663 - accuracy: 0.8012
Epoch 49/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4673 - accuracy: 0.7831
Epoch 50/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4154 - accuracy: 0.8012
Epoch 51/70
21/21 [==============================] - 0s 4ms/step - loss: 0.4387 - accuracy: 0.8072
Epoch 52/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4753 - accuracy: 0.7771
Epoch 53/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4279 - accuracy: 0.8253
Epoch 54/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4388 - accuracy: 0.8072
Epoch 55/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4493 - accuracy: 0.7892
Epoch 56/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4629 - accuracy: 0.7771
Epoch 57/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4640 - accuracy: 0.8133
Epoch 58/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3526 - accuracy: 0.8614
Epoch 59/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3795 - accuracy: 0.7892
Epoch 60/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4330 - accuracy: 0.8012
Epoch 61/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3794 - accuracy: 0.8494
Epoch 62/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4298 - accuracy: 0.7771
Epoch 63/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4425 - accuracy: 0.8133
Epoch 64/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3858 - accuracy: 0.8072
Epoch 65/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3868 - accuracy: 0.7831
Epoch 66/70
21/21 [==============================] - 0s 3ms/step - loss: 0.4102 - accuracy: 0.8072
Epoch 67/70
21/21 [==============================] - 0s 4ms/step - loss: 0.3624 - accuracy: 0.8373
Epoch 68/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3746 - accuracy: 0.8313
Epoch 69/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3666 - accuracy: 0.8373
Epoch 70/70
21/21 [==============================] - 0s 3ms/step - loss: 0.3826 - accuracy: 0.8434

In [86]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 534us/step - loss: 0.5689 - accuracy: 0.7619

[0.5688827633857727, 0.761904776096344]

In [87]:
y_test

     60_R
58      1
63      1
35      1
19      1
59      1
56      1
83      1
105     0
121     0
76      1
206     0
132     0
5       1
55      1
78      1
117     0
70      1
46      1
142     0
1       1
2       1
102     0
10      1
165     0
49      1
6       1
39      1
130     0
20      1
134     0
103     0
87      1
75      1
180     0
60      1
148     0
171     0
69      1
202     0
169     0
168     0
173     0

In [88]:
y_pred=model.predict(x_test)
Y_pred1=np.round(y_pred)
print(Y_pred1[0])

2/2 [==============================] - 0s 5ms/step
[1.]